
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - dertinfo-swa

variables:
  buildConfiguration: 'Release'

stages:
- stage: 'DeployToTest'
  displayName: 'Deploy To Test'
  jobs:
    - deployment: 'DeployToTest'
      environment: 'Test'
      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self
              submodules: true
            - task: AzureStaticWebApp@0
              inputs:
                app_location: "/dertinfo-swa/client"
                api_location: "/dertinfo-swa/functions"
                output_location: "dist"
              env:
                azure_static_web_apps_api_token: $(staging_deployment_token)

- stage: 'DeployToLive'
  displayName: 'Deploy To Live'
  dependsOn: 'DeployToTest'
  jobs:
    - deployment: 'DeployToLive'
      environment: 'Live'
      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self
              submodules: true
            - task: AzureStaticWebApp@0
              inputs:
                app_location: "/dertinfo-swa/client"
                api_location: "/dertinfo-swa/functions"
                output_location: "dist"
              env:
                azure_static_web_apps_api_token: $(live_deployment_token)


