
trigger:
  branches:
    include:
      - main

# Do not trigger the pipeline on pull requests
pr:
  branches:
    exclude:
      - '*'

variables:
  buildConfiguration: 'Release'

stages:
- stage: 'DeployToTest'
  displayName: 'Deploy To Test'
  jobs:
    - deployment: 'DeployToTest'
      environment: 'Test'
      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self
              submodules: true
            - task: AzureStaticWebApp@0
              inputs:
                app_location: "src/client"
                api_location: "src/functions"
                app_build_command: "npm install --force && npm run ado-build-ui-test"
                output_location: "dist"
              env:
                azure_static_web_apps_api_token: $(staging_deployment_token)

- stage: 'DeployToLive'
  displayName: 'Deploy To Live'
  dependsOn: 'DeployToTest'
  jobs:
    - deployment: 'DeployToLive'
      environment: 'Live'
      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self
              submodules: true
            - task: AzureStaticWebApp@0
              inputs:
                app_location: "src/client"
                api_location: "src/functions"
                app_build_command: "npm install --force && npm run ado-build-ui-prod"
                output_location: "dist"
              env:
                azure_static_web_apps_api_token: $(live_deployment_token)


